version: "3.0"
services:
  load_balancer:
    image: nginx:alpine
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
  app1:
    build: ./app1
    container_name: app1
  app2:
    build: ./app2
    container_name: app2
